import { useRouter } from "next/router";
import type { NextPageWithLayout } from "../_app";
import Head from "next/head";
import { skillNameArray, skillIcon } from "../../utils/constants";

import { trpc } from "../../utils/trpc";

const Rs3: NextPageWithLayout = () => {
  const router = useRouter();
  const { username } = router.query;
  const fetchName = typeof username === "string" ? username : "";

  const { data, isFetching } = trpc.user.getUserStats.useQuery(
    {
      username: fetchName,
    },
    {
      retry: false,
      refetchOnMount: false,
      refetchInterval: false,
      refetchOnReconnect: false,
      refetchOnWindowFocus: false,
      refetchIntervalInBackground: false,
    }
  );

  const skills = data?.skills;

  const formatXp = (xp: number) => {
    if (xp.toString().endsWith("00000000") && xp > 1000000000) {
      return (xp.toLocaleString().slice(0, -10) + "b").replace(",", ".");
    }

    if (xp.toString().endsWith("000000")) {
      return xp.toLocaleString().slice(0, -8) + "m";
    }

    return xp.toLocaleString();
  };

  return (
    <>
      <Head>
        <title>{username} Stats</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-w-screen flex min-h-screen flex-col items-center justify-start bg-zinc-900 p-10 text-white">
        {!isFetching && skills ? (
          <>
            <h1 className="mb-4 text-4xl font-bold">
              {fetchName.split("+").join(" ")}
            </h1>
            <h1 className="mb-4 text-4xl font-bold">
              {skills.at(0).xp.toLocaleString()}
            </h1>
            <table className="w-80 table-auto rounded border-2 border-zinc-700 text-left text-xl">
              <thead className="font-bold">
                <tr>
                  <th className="px-8 py-4">Skill</th>
                  <th className="px-8">Rank</th>
                  <th className="px-8">Level</th>
                  <th className="px-8">Xp</th>
                  <th className="px-8">Gain</th>
                </tr>
              </thead>
              <tbody>
                {skills.map((skill, i) => (
                  <tr
                    key={skill.skillId}
                    className={`${
                      i % 2 === 0 ? "bg-forest-700" : "bg-zinc-900"
                    }`}
                  >
                    <td className="flex items-center px-8 py-2">
                      {iconTemplate(skill.skillId)}
                      {skillNameArray[skill.skillId]}
                    </td>
                    <td className="px-8">{skill.rank.toLocaleString()}</td>
                    <td className="px-8">{skill.level}</td>
                    <td className="px-8">{formatXp(skill.xp)}</td>
                    <td className="px-8">{0}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </>
        ) : (
          <>
            <h1 className="text-4xl font-bold">Loading...</h1>
            <div className="flex h-14 w-14 animate-spin items-center justify-center rounded-full bg-gradient-to-tr from-indigo-500 to-pink-500">
              <div className="h-9 w-9 rounded-full bg-transparent"></div>
            </div>
          </>
        )}
      </main>
    </>
  );
};

const iconTemplate = (skillId: number) => (
  <img className="mr-2 w-5" src={skillIcon(skillId).src} />
);

export default Rs3;
