import { useRouter } from "next/router";
import { useState } from "react";
import type { NextPageWithLayout } from "../_app";
import Head from "next/head";
import { skillNameArray } from "../../utils/constants";

import { trpc } from "../../utils/trpc";

const Rs3: NextPageWithLayout = () => {
  const router = useRouter();
  const { username } = router.query;
  const [search, setSearch] = useState(username);

  // check if username is a string
  if (typeof username !== "string") {
    return <div>Username is not a string</div>;
  }

  const { data, isFetching } = trpc.user.getUserStats.useQuery({
    username,
  });

  const skills = data?.skills;

  const formatXp = (xp: number) => {
    if (xp.toString().endsWith("00000000") && xp > 1000000000) {
      return (xp.toLocaleString().slice(0, -10) + "b").replace(",", ".");
    }

    if (xp.toString().endsWith("000000")) {
      return xp.toLocaleString().slice(0, -8) + "m";
    }

    return xp.toLocaleString();
  };

  return (
    <>
      <Head>
        <title>{username} Stats</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-start p-4">
        <div className="mb-20">
          <input
            type="text"
            className="mb-2 block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500"
            placeholder="Username"
            required
            onChange={(e) => setSearch(e.target.value)}
          />
          <button
            onClick={() => router.push(`/rs3/${search.split(" ").join("+")}`)}
            className="rounded bg-blue-500 py-2 px-4 font-bold text-white hover:bg-blue-700"
          >
            Search
          </button>
          {isFetching && <p>Fetching...</p>}
        </div>
        <h1 className="mb-4 text-4xl font-bold">{username}</h1>
        <h1 className="mb-4 text-4xl font-bold">
          {skills?.at(0).xp.toLocaleString()}
        </h1>
        <table className="w-80 table-auto text-left text-xl">
          <thead>
            <tr>
              <th className="px-8">Skill</th>
              <th className="px-8">Rank</th>
              <th className="px-8">Level</th>
              <th className="px-8">Xp</th>
            </tr>
          </thead>
          <tbody>
            {skills?.map((skill) => (
              <tr key={skill.skillId}>
                <td className="px-8">{skillNameArray[skill.skillId]}</td>
                <td className="px-8">{skill.rank.toLocaleString()}</td>
                <td className="px-8">{skill.level}</td>
                <td className="px-8">{formatXp(skill.xp)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </main>
    </>
  );
};

export default Rs3;
