import { useRouter } from "next/router";
import type { NextPageWithLayout } from "../../_app";
import Head from "next/head";

import { trpc } from "../../../utils/trpc";
const Update: NextPageWithLayout = () => {
  const router = useRouter();
  const { id } = router.query;

  if (typeof id !== "string") {
    return <div>Invalid id</div>;
  }

  trpc.example.test.useQuery(
    {
      id,
    },
    {
      retry: false,
      refetchOnMount: false,
      refetchInterval: false,
      refetchOnReconnect: false,
      refetchOnWindowFocus: false,
      refetchIntervalInBackground: false,
    }
  );

  return (
    <>
      <Head>
        <title>Update</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-w-screen flex min-h-screen flex-col items-center justify-start bg-zinc-900 p-10 text-white">
        <h1>Update</h1>
      </main>
    </>
  );
};

export default Update;
