import { useState } from "react";
import { useRouter } from "next/router";
import type { NextPageWithLayout } from "./_app";
import Head from "next/head";
const Rs3: NextPageWithLayout = () => {
  const router = useRouter();
  const [search, setSearch] = useState("");

  return (
    <>
      <Head>
        <title>Runescape 3 Stats</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-start p-4">
        <div className="mb-20">
          <h1 className="mb-4 text-4xl font-bold">Welcome!</h1>
        </div>
      </main>
    </>
  );
};

export default Rs3;
